language: python
python:
  - "3.7"

notifications:
  email:
    recipients:
      - ilja.gubin@gmail.com
    on_success: never # default: change
    on_failure: change # default: always

install:
  - pip install -r requirements.txt

script:
  - echo "Skipping tests for now, just deploy"

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "c10m0+jTW9L88C90XA7pHjqLxy0SLJ5kJNszB/nrd9mtf2c5K+OpVHK8w4JGDobjiOgaQTWPKjoaYuPjNZmSCSE2uZxZjCYcuK9XFwIP9uC7wDnhO7aW4/zCxt+Qptfpy/Jk0db3tyPZzGS9UnOrNndlaPZkn5JhUaTnfb7uBh2uwlBcRCW+nlnIS/3VzlXTBLMi5+XaIlCvCY6boyAG0ov8kQU7ZU9zCikIxgEvt9SDER+T4TdeOAIdnDVxnuj3foEDITR+KVzbf9QJKV14xKGVBSr0mRFAcsfxTiMXx1PE48BeoZq/dT5fs7pwkX109reWbh1zceFXRvVemBXy6itjRayDCtOuPENZKxTlm5dGimIPx1sYAlmMBHiYiNNaXJ0SjX45LFAIu/JSKy6HhV5ZefA0Ui2+BnX9gZsp9jFYWy1x38NpAeGS7/KwO7CD+5ezk+WfMlvlGZ1eY0E7twurWparsK1kVIyql7lJQc/1fWULRbRcmIVbPqsm56aOc0A9mTu46UN2WsvLTFOwabitzhSD+wWR/v6KY/Mi4foSa2tLWDVzSWzhi46kPlu0YFYhG5FBcUROGoOopAa2r0fwHqQNBR0T03chaAZ5bMiZqDaW2GDKelXnRJ/7wthsbGPHXjhwDprbEzP4SqkcuBnIne0ajRqLFcbz09TFuo4="
    skip_existing: true