language: python
python:
  - "3.7"

notifications:
  email:
    recipients:
      - ilja.gubin@gmail.com
    on_success: never # default: change
    on_failure: change # default: always

install:
  - pip install -r requirements.txt

script:
  - echo "Skipping tests for now, just deploy"

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "KbzAAvLj3n3vKQdiXZ9TE53lbOpi8BcOjb9iAde4u0TlG0NlErYIh90cnBmstu7hnsFSV7VFc3Znp8BlYjQ55SM1cEPqu3CJiBW04lOYCE6f7fxHQsC0feMV+kEvXlTPbkmNBX/Pz4HxLZ2rv5QQgTTuoMhM3tkMvd5NAoZ5/6yNbgvM8ffKns0XWGXDCYTupWvowJgHBqedCqU/IKeNxB0xkZkv/jSXgLbXsX01CHYqwxECSFetSiF48fKtQv8pnCXAzRCbZLE13gl0Lp0nRSi6omo0drnf8d9ZI7taQuXlBNHKh/4kWOjFb3/an9RQfJVlErmFAZum4NIoy85WM0hN0mohHQr3aXAoGXLAdnwkxdMpO9cGNBRywN5cjPJOv+BhE6bezmsw0gRkPNnHLizLQk5v4J9PCEj/OsqRPCwU3AUJKMGc/MgnXyy5mq6c1YRmwB16EBb3MGsHJqiQ4QmFhSDBpW18BV3YaQGTgKVkQNpEMQYrcFimTeeAFE1w905gw3YBQzdS4SExVY/+n9MQ5C7MhE9OAJ8FWhO1ulwOllIl3KZfGn2HFHNLK2U8oijiMhwetQPCOR9tcbEPc+yO0ffV/+DbGOCMGOwr1qyfJjh8/RAD5p6wMH1TLsvzOx7/lJYjzE4oRrQhZje1k3VB6Lan/ygR0RITnPiPZ+c="
    skip_existing: true