language: python
python:
- '3.7'
notifications:
  email:
    recipients:
    - ilja.gubin@gmail.com
    on_success: never
    on_failure: change
install:
- pip install -r requirements.txt
script:
- echo "Skipping tests for now, just deploy"
deploy:
  provider: pypi
  user: __token__
  password:
    secure: lR8xMJddQfLCeKXqsXHSrTD3S+RlX5q4ykU0oKhFZ45YYuGts8yck2GgpmqbkL+TBW8vEkFKPt+scR5hEHDgyIcjUjnqzdiJpT1onGGKx234xTIKvzNU7Yk7oJpqNLp20UZMJO/VlriSnjJkJsctWiTa6LkFD64IKVr2PtrdN6NisXsYmagqiLjnrAzV6VkSi/d4wACu8+/yQ7xBpoYLoL+ZMLspjBCzpbQ5iwt+S6/U+CHQ1sooX4azHuZI1k7zX09Uqg6pOf3HxJzpVSmFzdJglHgJP3wQIq++M7c+4bpTBOAFYwYhcU2h/liezCjkGdK+FRYqHeR1e3nyk+5tLwRcgyzW72DMjeBSdeSSBmQdxGKdNdS1L6P2CcnSWfKo6IbkdJqLWVjIb9vsFx7w76SrVvCSKDVkiO93nUOC50skweTwz655V9HOqr4OPp3JGcCn8v2XVbzmo9uf7xA9grp1bN/56tzeZ32n1g8jDt+hSZ5t2Faxye0HAM/VBQCWx5Kd+l5pYGINz5V1R74UKM39mJ2C1fYqW+p9wSz8JYKGBWJOXbM9SRn2ysddaNsd94slFVPiKd+kpY34X78T2kf83qrq4nyLe3Gl1NkA9azFWJzVST//b2DB2rF54V++bxQgcOwXuEvTx3a0Ir4IKBd1b2GYl7QV5skk9ZrdPNY=
  distributions: sdist bdist_wheel
  skip_existing: true