language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

notifications:
  email:
    recipients:
      - ilja.gubin@gmail.com
    on_success: never # default: change
    on_failure: change # default: always

install:
  - pip install -r requirements.txt

script:
  - echo "Skipping tests for now, just deploy"

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "i/SQ8AyrsSuV75CRAFCeDcx8iVmRzIMmotKfn023+bCp+uTkhxtH6jE++hPzCD1KeeSWmFkDS4HQ4ikqcW30RNsn07dmu1B7z7q/Ke9gcwNLa/h4IoGB0x8zDviAM8IO8fTMj1979Od1iTxj1XAIIGLd3oMxOBSC3K9gLCnfJjfYpZQVTfIWa+SfXnBNEz0kZlqhXanEdP+02cnRnUo7N3JBv78/ZG6nJQkDvzjde/4y8nZ0vohKLm+oUOebu2EOMZVR273GZ2r+QTMa3A97V04u9C4LcLQc0YWVmdFH4CzTIOglAI5k7xpONCn3wK0WvNK5SI99I0yL4AtKbDqgPIsztcWemHjf9uULwjeWdeqRtlfk7/COREDoQ++G3KFxv0q/YvlkktLrISjWklzLoXTRo6YQGaosxOpVf318rZGM7heDp7sV7uJV5cgLH+Rkv/6wPSyPKxGSk2OY+uypVuQlOtPM6R23tnM9+Eud3f8WnXj9nFb/NI9TORMUZB/yFU25CBKc5vTakDwMWyFrPazpSrRYSOZ89NdquT4y30SmEfnuO3ZcMLdPvtmQmDbu6yyvuExcF7Y9ySDnTRPTISIPGdK+mtfeTfqDhovpwaWO2BilZva37P18tqr9peW/7P/7+EjuYvyZt79vxKL2Be8hbzCupZkBprrMGoqX/3g="
  skip_existing: true